### ISSUE TITLE
link to paper

### ISSUE THREAD

**Issue by jbloom** [dms-viz/dms-viz-docs#6]
@WillHannon-MCB: None of the GitHub repo, the docs, or anything in the tool link to the paper citation. You should add this. 

The docs even have an empty citation subsection [here](https://dms-viz.github.io/dms-viz-docs/introduction/what-is-dms-viz/)

**Comment by jbloom** [comment]
@WillHannon-MCB, just re-tagging this issue, which really needs to be fixed.

**Comment by WillHannon-MCB** [comment]
It's linked in the [docs](https://dms-viz.github.io/dms-viz-docs/project-info/contact-info/#citation), but it's not easy to find. I'll make it more obvious in each repo.
